export const products = [
  {
    id: 1,
    title: "CrashBandicoot N'Sane Trilogy",
    price: 15000,
    stock: 5,
    description: "Juego de plataforma",
    category: "Plataforma",
    img: "https://res.cloudinary.com/dyc9of3yj/image/upload/v1678540868/ImagenesMias/Crash_apsmv5.jpg",
  },
  {
    id: 2,
    title: "Fifa 19",
    price: 14500,
    stock: 5,
    description: "Juego de Deporte",
    category: "Deporte",
    img: "https://res.cloudinary.com/dyc9of3yj/image/upload/v1678540833/ImagenesMias/fifa_z7zfow.jpg",
  },
  {
    id: 3,
    title: "Mortal Kombat X",
    price: 19000,
    stock: 5,
    description: "Un clasico de pelea con más acción",
    category: "Pelea",
    img: "https://res.cloudinary.com/dyc9of3yj/image/upload/v1678540818/ImagenesMias/mortal_xqavzb.jpg",
  },
  {
    id: 4,
    title: "DragonBall SenoVerse xv",
    price: 17800,
    stock: 5,
    description: "Juego de Pelea",
    category: "Pelea",
    img: "https://res.cloudinary.com/dyc9of3yj/image/upload/v1678540866/ImagenesMias/dragonball_ssedi5.jpg",
  },
  {
    id: 5,
    title: "God of War: RAGNAROK",
    price: 24600,
    stock: 10,
    description: "Juego de Plataforma y Acción",
    category: "Plataforma y Acción",
    img: "https://res.cloudinary.com/dyc9of3yj/image/upload/v1680131348/ImagenesMias/GOW-RK_ag0cpy.webp",
  },
  {
    id: 6,
    title: "Call of Duty WARZONE Last Stand",
    price: 19350,
    stock: 7,
    description: "Juego de Batalla Campal",
    category: "Plataforma",
    img: "https://res.cloudinary.com/dyc9of3yj/image/upload/v1678540830/ImagenesMias/callduty_b6dyye.jpg",
  },
];
